
export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#221c4e]">
      
      <div className="max-w-3xl mx-auto px-4 py-16 prose">
        <h1>Terms of Service</h1>
        <p>Last updated: January 2024</p>

        <h2>Acceptance of Terms</h2>
        <p>By using Founder Weekly Growth Report, you agree to these terms of service.</p>

        <h2>Service Description</h2>
        <p>We provide a business dashboard and weekly reporting tool for ecommerce founders. The service includes data upload, metric calculations, dashboard visualization, and email reports.</p>

        <h2>Free Trial</h2>
        <p>New accounts receive a 7-day free trial with full access to all features. After the trial expires, you can upgrade to continue using the service.</p>

        <h2>Your Data</h2>
        <p>You retain ownership of all data you upload or enter. We process your data only to provide the service. You can export or delete your data at any time.</p>

        <h2>Acceptable Use</h2>
        <p>You agree not to misuse the service, attempt to access other users&apos; data, or use the service for illegal purposes.</p>

        <h2>Limitation of Liability</h2>
        <p>The service is provided as-is. We are not liable for business decisions made based on the reports generated by the service.</p>

        <h2>Changes to Terms</h2>
        <p>We may update these terms. Continued use after changes constitutes acceptance.</p>
      </div>
    </div>
  )
}
